### ISSUE TITLE
All is I see is a RaspberryCast splash screen

### ISSUE THREAD

**Issue by Sachin1968** [vincelwt/RaspberryCast#19]
Installed on a Pi 3, I can access the Remote via http or the Android app. I'm also able to add videos to the queue via the Chrome extension but all I see on the Pi screen is a screen that says RaspberryCast is ready.

Any suggestions?

Thanks, I really want this to work!

**Comment by vincelwt** [comment]
Hello, 

Could you provide the log, located at _/home/pi/RaspberryCast/RaspberryCast.log_ ?

**Comment by edberteliezer** [comment]
same problem. could be related to ip adress? its set to raspberry.local

**Comment by edberteliezer** [comment]
here is a log file pastebin.com/9JUc0ErX

**Comment by edberteliezer** [comment]
so basically every video i casted returns [0;31mERROR:[0m no suitable InfoExtractor for URL

**Comment by vincelwt** [comment]
@edberteliezer Thanks for posting a log.

For the Youtube videos it seems that youtube-dl isn't working (as #22 ). Could you try manually reinstalling it ?

**Comment by vincelwt** [comment]
Also, the first videos in the log doesn't seem to come from YouTube, except bug from RaspberryCast end. Does they come from YouTube ? Or from another Google service (like it seems) ?

**Comment by edberteliezer** [comment]
I will try reinstalling the youtube-dl. And yes, the first video is from a google service, presumably Google Drive, uploaded and extracted the direct video stream url using, presumably, similar method of youtube-dl -g [URL]. It is actually a.. um.. 'fan reupload' of.. a thing that was on TV :)

**Comment by vincelwt** [comment]
Ok, thanks for pointing this out. The problem with these videos is that youtube-dl try to extract the url. I will try to correct this soon

**Comment by edberteliezer** [comment]
Ok, so pip is bugged
https://github.com/pypa/pip/issues/2964#issuecomment-137346639
https://github.com/pypa/pip/issues/2964#issuecomment-192607458

I suppose I will uninstall with apt-get

**Comment by edberteliezer** [comment]
now both chrome and remote web says please make sure link/action is compatible. I will try removing the RaspberryCast and Youtube-dl and reinstall them is thats a help

**Comment by edberteliezer** [comment]
So, after tinkering in the web for a while, I installed youtube-dl with pip --ingnore-installed. and again with --upgrade. Now, I can properly uninstall and install again with pip. 

And the result is ERROR PLEASE MAKE SURE LINK IS COMPATIBLE. 

Log file: http://pastebin.com/V8DC5MZU

**Comment by vincelwt** [comment]
Thanks for trying. Your issue the same as #22 . 
I think it may be due to new versions of youtube-dl which changed the output data structure.

Will make some tests this week

@Sachin1968 could you try to reinstall youtube-dl too ?

**Comment by edberteliezer** [comment]
Well Good luck then. So far you are the only promising mp4 / youtube-dl url 'omx caster' that is up-to date. Most of my findings are from 2012-2014 which is out dated etc. Also, current on-going 'mirroring' project worth taking a look: https://www.youtube.com/watch?v=yhxnAmJsT_E&feature=youtu.be&list=PLT2HCg4Nbo1upDmqPFxyT8koQwvCcUOph | Maybe you can collaborate for experimental mirroring button or something. The problem with that project is it installs other presentation stuff which I dont need and too many commands to input which will take some times to read and figure out.

**Comment by mheine** [comment]
This issue is now almost 2 years old, and as such I'm closing it.
