### ISSUE TITLE
Startup Temporary Bricks pi 3

### ISSUE THREAD

**Issue by zapinator3000** [vincelwt/RaspberryCast#26]
At first, I had to chmod 777 everything in the folder to allow Raspberry Cast to have permission to read it however, when I did that Update still fails with "Permission Denied" and I get a slash screen and It completely bricks my pi until reboot. When I try to access the log file, there is nothing in it.

**Comment by mheine** [comment]
Closing issue to due old age and inactivity - feel free to re-open if the problem arises again 🙂
