### ISSUE TITLE
Does this still have active development?

### ISSUE THREAD

**Issue by 4k-developer** [vincelwt/RaspberryCast#35]
The Youtube-DL problem hasn't seemingly been resovled yet and the issues are from 2016 so is someone still working on it?

**Comment by vincelwt** [comment]
Hi,
I don't really use my Raspberry Pi anymore so no, it is not under active development, for now. 
Maybe that'll change in the future if I come back to my Raspberry Pi, but I can't guarantee it.

**Comment by 4k-developer** [comment]
Oh okay
