### ISSUE TITLE
Assumes user PI on installation?

### ISSUE THREAD

**Issue by pcs3rd** [vincelwt/RaspberryCast#43]
Why would a script automatically specify the user "pi"? I don't have a user "Pi" on my raspbian installation and can't install because this assumes the user pi. there are simple ways to fix this. For example use
echo "FOO"
 Read user
cd $user

**Comment by vincelwt** [comment]
Feel free to submit a PR, I don't maintain it really anymore (for now)

**Comment by pcs3rd** [comment]
Ok. but what's a PR? i dont store mutch code on gh

**Comment by vincelwt** [comment]
**P**ull **R**equest, a way to contribute to Git repositories (see [this page](https://help.github.com/articles/about-pull-requests/))
If you want to contribute to RaspberryCast.

**Comment by vincelwt** [comment]
Fixed by #44
