### ISSUE TITLE
Licensing 

### ISSUE THREAD

**Issue by mheine** [vincelwt/RaspberryCast#46]
RaspberryCast ought to have a license, even if it seems unnecessary. I would suggest a broad license in order to not limit anyone, and I would choose the MIT License. Any thoughts @vincelwt ?

**Comment by vincelwt** [comment]
There already is a mention about using the MIT license in the README, not sure if it's really necessary to add the file ?

**Comment by mheine** [comment]
I missed that, embarrassingly enough. I’ll add a stand-alone file anyway, as it makes it easier for GitHub to categorize the project 😊
