### ISSUE TITLE
RaspberryCast block window manager

### ISSUE THREAD

**Issue by wdor** [vincelwt/RaspberryCast#48]
Dear all,

Since yesterday (but I restart my PI at this time), I have a bug with RapsberryCast and vnc.

Config: 
- PI 3 / Raspbian 9.3
- Kodi 17.6
- LXDE
- RaspberryCast

When PI start, automatically, it launchesRaspberryCast (I tried with rc.local and cron), them kodi (through autostart in lxsession).
On the main screen, Kodi is working fine
On VNC: blackscreen

After testing all options, if I disable RaspberryCast, I'm able to access the PI through VNC.

I tested also another option: disabled kodi and let RaspberryCast only.
I see the splashscreen on my main screen, but no possibility to access vnc. If vnc start quickly, I see the screen, but all my inputs are disabled (no possibility to launch something  through the vnc gui). With a keyboard directly attached to the PI3, I found the problem: if I click 2 or 3 times on the enter button, the splash screen disappear and VNC is working well.

So I disabled the RaspberryCast autostart. 
Everything is working well until I launch manually the RaspberryCast.

As soon as I launch the command, I lose the "VNC input" (meaning no more keyboard or mouse interaction). I'm able to retreive them by using the attached keyboard on PI (and if kodi is launched, I have first to stop kodi, them click 2 or 3 times on enter to disable the RaspberryCast splash screen.

So what is the problem?
How can I solve that?

Thanks for your feedback

**Comment by vincelwt** [comment]
Hi,
you can try changing `new_log` to **false** in the  _raspberrycast.conf_ file (and restart)
