### ISSUE TITLE
Play music files in background

### ISSUE THREAD

**Issue by sid-gpt** [vincelwt/RaspberryCast#54]
Hi
Is there any way with which music from Soundcloud or Spotify can be played in background.
Also can we display the title of the current file.

**Comment by mheine** [comment]
I would think that it would go beyond the scope of RaspberryCast. Try using something like [PiMusicBox](http://www.pimusicbox.com/), with RaspberryCast running in the background?

**Comment by vincelwt** [comment]
I agree, this is not in the scope of RaspberryCast, although you should already be able to cast what is compatible with youtube-dl including some audio services (https://rg3.github.io/youtube-dl/supportedsites.html)
