### ISSUE TITLE
I get SyntaxError: invalid syntax when I try to run Raspicast (the server.py script) on Arch Linux ARM

### ISSUE THREAD

**Issue by qwxy0** [vincelwt/RaspberryCast#56]
I've been trying to install RaspberryCast on Arch Linux ARM manually. After following the install script and tracking down dependencies needed for RaspberryCast on Arch ARM and after cloning the git(hub) repo, when I try to start RaspberryCast I get the following error:

[alarm@alarmpi RaspberryCast]$ ./RaspberryCast.sh start
Checking for updates.
Already up to date.
Starting RaspberryCast server.
Done.
[alarm@alarmpi RaspberryCast]$   File "./server.py", line 109
    except Exception, e:
                    ^
SyntaxError: invalid syntax

Any insight into the error would be much appreciated. Could it be due to the version of python3 being too new or missing some module? I don't know really.
Thank you for your help

**Comment by mheine** [comment]
I don't run Arch myself, but that does sound like a Python 2/3 version issue, and would probably be fixed by ensuring that you run it using Python 2 🙂

**Comment by jarondl** [comment]
Yes, indeed, that is because of Python2/3 differences. RaspberryCast should definitely support python3, but for now you can work around this by reinstalling your dependencies with Python2 and running:

    python2 server.py &
