### ISSUE TITLE
[question] how can I view the videos in the playlist?

### ISSUE THREAD

**Issue by helen-fornazier** [vincelwt/RaspberryCast#71]
Hi,

First of all, thanks for this project, is it great!

I added some videos from youtube to the playlist, it works, but is it possible to view the videos that are currently in the play list? Also, if is it possible to manipulate the playlist (delete some videos, clean the list)

Thanks

**Comment by vincelwt** [comment]
Hi,
Unfortunately, this is not possible at the moment. 
There is already a feature request opened for it: https://github.com/vincelwt/RaspberryCast/issues/14
Cheers,
Vincent

**Comment by helen-fornazier** [comment]
Nice.

Sorry, I didn't see this feature request, thanks for pointing me to it.

**Comment by mheine** [comment]
@helen-fornazier If you're interested in working on it, there's a (rather empty) branch called `manage-playlist ` that you can use as a starting point if you want :slightly_smiling_face:

**Comment by helen-fornazier** [comment]
@mheine Cool, I'll take a look when I have so time, thanks
