### ISSUE TITLE
Suggestion: cast a playlist

### ISSUE THREAD

**Issue by buzzbo** [vincelwt/RaspberryCast#9]
This is not an issue per se, but I was wondering if it might be possible to cast a youtube playlist. Thoughts?

**Comment by LoicLWRT** [comment]
Indeed, it is not possible at the moment to cast a playlist, that would be a great feature and quite easy to implement. 
Unfortunately the current playlist management is fairly limited, we'd have to improve that beforehand.
As for the current implementation, I believe RaspberryCast will only cast the video present in the URL.

**Comment by vincelwt** [comment]
Glad to inform it is now possible to cast a playlist :+1: 
Works with Youtube and Soundcloud as of today.

I recommend doing a fresh install, because we made quite a lot of modifications.
